#!/usr/bin/env bash
set -e

declare -a LOCALES=(
    "fr"
)

ROOT=$(realpath $(dirname $0)/..)

for SOURCE in $(find ${ROOT}/content -type f -iname *.en.md); do
    for LOCALE in "${LOCALES[@]}"; do
        DEST="${SOURCE%.en.md}.${LOCALE}.md"

        if [[ ! -f ${DEST} ]]; then
            echo "Creating fallback for ${DEST#${ROOT}/content/}"
            cp ${SOURCE} ${DEST}
        fi
    done
done
